Installed Anaconda and tensorflow 2.15,keras,flash

from tensorflow.keras.layers import Dense, Flatten, Input
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img
from tensorflow.keras.applications.xception import Xception, preprocess_input
from glob import glob
import numpy as np
import matplotlib.pyplot as plt

train_datagen = ImageDataGenerator(rescale=1. / 255,
                                   shear_range=0.2,
                                   zoom_range=0.2,
                                   horizontal_flip=True)
test_datagen = ImageDataGenerator(rescale=1. / 255)

training_set = train_datagen.flow_from_directory('preprocessed dataset/training', target_size=(229, 229), batch_size=32,
                                                 class_mode='categorical')

test_set = test_datagen.flow_from_directory('preprocessed dataset/testing', target_size=(229, 229), batch_size=32,
                                            class_mode='categorical')
imageSize = [229, 229]

xception = Xception(input_shape=imageSize + [3], weights='imagenet',include_top=False)

for layer in xception.layers:
    layer.trainable = False

x = Flatten()(xception.output)

model = Model(inputs=xception.input, outputs=prediction)

model.compile(
    loss="categorical_crossentropy",
    optimizer="adam",
    metrics=['accuracy']
)

r = model.fit(training_set,
              validation_data=test_set,
              epochs=30,
              steps_per_epoch=len(training_set) // 32,
              validation_steps=len(test_set) // 32
              )
